---
version: "3.8"
services:

  # grocy:
  #   image: lscr.io/linuxserver/grocy:latest
  #   container_name: grocy
  #   priviledged: true
  #   env_files:
  #     - .env.common
  #     - 
  #     - 
  #   volumes: 
  #     -  
  #     - 
  #     - 
  #   labels:
  #    - "traefik.docker.network=utilities"
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.$BAG.rule=Host(`$BAG.$DOMAIN`)"
  #    - "traefik.http.routers.$BAG.entrypoints=https"
  #    - "traefik.http.routers.$BAG.tls=true"
  #    - "traefik.http.routers.$BAG.service=${BAG}_svc"
  #    - "traefik.http.routers.${BAG}.middlewares=chain-authelia@file"
  #    - "traefik.http.routers.$BAG.tls.certresolver=myresolver"
  #    - "traefik.http.services.${BAG}_svc.loadbalancer.server.port=443"  
    # networks:
    #   - utilities      
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    restart: always
    env_file:
      - .env.common
      - .env.$NBXYZ
    volumes: 
      - /config/utilities/netbootxyz/config:/config
      - /config/utilities/netbootxyz/assets:/assets
    expose:
      - 3000
      - 69
      - 80
    labels:
      - "traefik.docker.network=utilities"
      - "traefik.enable=true"
      - "traefik.http.routers.$NBXYZ.rule=Host(`$NBXYZ.$DOMAIN`)"
      - "traefik.http.routers.$NBXYZ.entrypoints=https"
      - "traefik.http.routers.$NBXYZ.tls=true"
      - "traefik.http.routers.$NBXYZ.service=${NBXYZ}_svc"
      - "traefik.http.routers.$NBXYZ.middlewares=chain-authelia@file"
      - "traefik.http.routers.$NBXYZ.tls.certresolver=myresolver"
      - "traefik.http.services.${NBXYZ}_svc.loadbalancer.server.port=3000" 
    networks:
      - utilities

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    expose:
      - 3000
    env_file: 
      - .env.common
      - .env.$HP
    volumes:
      - /config/utilities/homepage:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=utilities"
      - "traefik.enable=true"
      - "traefik.http.routers.$HP.rule=Host(`www.$DOMAIN`) || Host(`$HP.$LOCAL.$DOMAIN`)"
      - "traefik.http.routers.$HP.entrypoints=https"
      - "traefik.http.routers.$HP.tls=true"
      - "traefik.http.routers.$HP.service=${HP}_svc"
      - "traefik.http.routers.$HP.middlewares=chain-authelia@file"
      - "traefik.http.routers.$HP.tls.certresolver=myresolver"
      - "traefik.http.services.${HP}_svc.loadbalancer.server.port=3000" 
    networks:
      - utilities

  shlink:
    image: shlinkio/shlink:stable
    restart: always
    container_name: shlink-backend
    env_file:
      - .env.common
      - .env.$SHLB
    depends_on:
      - database
    expose:
      - 8080
    networks:
      - shlink

  database:
    image: mariadb:latest
    restart: always
    container_name: shlink-database
    env_file:
      - .env.common
      - .env.$SHLDB
    volumes:
      - /config/utilities/shlink/mariadb:/var/lib/mysql
    networks:
      - shlink

  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    container_name: shlink
    volumes:
      - /config/utilities/shlink/web/servers.json:/usr/share/nginx/html/servers.json
    depends_on:
      - shlink
    expose:
      - 80
    labels:
      - "traefik.docker.network=utilities"
      - "traefik.enable=true"
      - "traefik.http.routers.$SHL.rule=Host(`$SHL.$DOMAIN`) || Host(`$SHL.$LOCAL.$DOMAIN`)"
      - "traefik.http.routers.$SHL.entrypoints=https"
      - "traefik.http.routers.$SHL.tls=true"
      - "traefik.http.routers.$SHL.service=${SHL}_svc"
      - "traefik.http.routers.$SHL.middlewares=chain-authelia@file"
      - "traefik.http.routers.$SHL.tls.certresolver=myresolver"
      - "traefik.http.services.${SHL}_svc.loadbalancer.server.port=80" 
    networks:
      - utilities
      - shlink
networks:
  utilities:
    name: "utilities"
  shlink:
    name: "shlink"


