networks:
  t2_proxy:
    external: true
    name: "t2_proxy"
  t3_proxy:
    external: true
    name: "t3_proxy"

services:
  traefik:

    command:
      - "--experimental.hub=true"
      - "--hub.tls.insecure=false"
      - "--metrics.prometheus.addrouterslabels=false"
      - "--configFile=/config/traefik.yml"

    container_name: "traefik"

    entrypoint:
      - "/entrypoint.sh"

    environment:
      - "PUID=969"
      - "PGID=1001"
      - "TZ=Europe/Madrid"
      - "OVH_ENDPOINT=ovh-eu"
      - "OVH_APPLICATION_KEY=bb1483866aaa2639"
      - "OVH_APPLICATION_SECRET=9d9676d7a6f88d0e76a4986ec4da3ad4"
      - "OVH_CONSUMER_KEY=04b1a9f485ae816b9a68b7d1220a3ef9"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "gateway.docker.internal:host-gateway"

    hostname: "47991c7e04bd"

    image: "traefik:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "fbf381ee9ab9445dae0b4c17f45e0366148fad72499aeac2a656898b79bd439f"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "traefik"
      com.docker.compose.project.config_files: "docker-compose.yml"
      com.docker.compose.project.working_dir: "/config/traefik"
      com.docker.compose.service: "traefik"
      com.docker.compose.version: "1.29.2"
      org.opencontainers.image.description: "A modern reverse-proxy"
      org.opencontainers.image.documentation: "https://docs.traefik.io"
      org.opencontainers.image.source: "https://github.com/traefik/traefik"
      org.opencontainers.image.title: "Traefik"
      org.opencontainers.image.url: "https://traefik.io"
      org.opencontainers.image.vendor: "Traefik Labs"
      org.opencontainers.image.version: "v2.10.7"
      traefik.docker.network: "t2_proxy"
      traefik.enable: "true"
      traefik.http.routers.api.entrypoints: "https"
      traefik.http.routers.api.middlewares: "chain-authelia@file"
      traefik.http.routers.api.rule: "Host(`traefik.prat.ketfrix.es`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.certresolver: "myresolver"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "t3_proxy"
      - "t2_proxy"

    ports:
      - "443:443/tcp"
      - "80:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "/config/traefik/letsencrypt:/letsencrypt"
      - "/config/traefik/logs:/logs"
      - "/config/traefik/plugins:/plugins-local"
      - "/config/traefik/rules:/rules"
      - "/config/traefik:/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

version: "3.6"

